name: isolated_http_client
description: http clint with requests cancelation and isolate decoding in separated isolate
version: 1.6.2
homepage: https://github.com/Renesanse/isolated_http_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cross_file: ^0.3.3+2
  http: ^0.13.5
  http_parser: ^4.0.2
  worker_manager: ^4.4.6
  shared_preferences: ^2.0.15

dev_dependencies:
  lint: ^1.10.0
